### ISSUE TITLE
Should not add go sources files in `srcs` of `proto_library()`

### ISSUE THREAD

**Issue by sfirmery** [please-build/puku#57]
With a folder containing a BUILD file with a `proto_library()`, a proto file and a go file.

`puku fmt` adds the go source file in `srcs` of the `proto_library()`.

Same with an explicit `libKinds` for `proto_library` with `"nonGoSources": true`.

**Comment by Tatskaari** [comment]
I found an issue with custom kinds, however I've not been able to reproduce for the `proto_library` kind. I've raised a PR here to fix  the issue I found here: #60

Are you sure you're on the latest version of puku?

**Comment by sfirmery** [comment]
Yes, I'm using puku v1.0.0.

Here a repository that can reproduce it: https://github.com/sfirmery/puku_proto_issue

After `plz run //tools:puku -- fmt //testproto/...`, the `proto_library()` in `testproto/BUILD` contains the go source file in `srcs`.

**Comment by sfirmery** [comment]
After more tests, it seems to be related to the package name of the go source file that match the `proto_library()` name. If I change the go source file package name, puku no longer add it.

**Comment by Tatskaari** [comment]
Hey! I think this is the same issue that I described here:
https://github.com/please-build/puku/issues/63

It's ambiguous to puku about which target to resolve the import to, as there are essentially 2 library targets in the package as far as puku understands. Let me know if that doesn't make sense and you'd like to re-open this issue.
