### ISSUE TITLE
WARNING couldn't resolve "slices" for //test:main: can't find module .

### ISSUE THREAD

**Issue by sfirmery** [please-build/puku#84]
In version 1.3.1, using the binary linux_amd64 from https://github.com/please-build/puku/releases/tag/v1.3.1, when a go source file imports `slices` (replacement of [golang.org/x/exp/slices)](https://pkg.go.dev/golang.org/x/exp/slices) since go1.21), a warning is print:

    WARNING couldn't resolve "slices" for //test:main: can't find module .

I tried to reproduce it but the binary of `plz build //package:puku_linux_amd64` from the tag v1.3.1, did not print any warning.

**Comment by Tatskaari** [comment]
I think this depends on what `build.GoRoot` returns. Puku tries to find package in there, but maybe that's inferred from the go sdk it was compiled with.

**Comment by sfirmery** [comment]
I've done more tests, and it seems that it's because of my GOROOT that is incorrect.

With the switch to puku, I also split the toolchain and the stdlib with `go_stdlib()`. GOROOT was set to the toolchain folder. But as the toolchain folder no longer contains the stdlib, I think GOROOT must now be set to the stdlib folder.

Setting GOROOT to the stdlib folder seems to fix the issue.

**Comment by Tatskaari** [comment]
Newer versions of Puku should handle this better. We generate the GOROOT imports at compile time from the version of the toolchain puku uses.
